### ISSUE TITLE
Compatibility questions WT_CJ4_v0.12.13

### ISSUE THREAD

**Issue by hiddencreative** [dementedmonkey/cj4-mcdu#22] opened 2022-05-24 15:06 UTC
Before downloading and installing,  I have compatibility question.  The newest version of the WT CJ4 is 0.12.13, and the mod says only good for 0.12.12.  Will this work with the newest version?  If not, is that an easy update?

**Comment by r-flo-r** [comment] 2022-08-24 18:17
hi. i am running v.0.2.0 with the WT CJ4 v0.12.13 for quite a while now and can say i had no issues.

**Comment by pennylanerebel** [comment] 2022-08-25 15:48
I can confirm, too that everything is working fine with 0.12.13 /Many thanks to the author.

**Comment by dementedmonkey** [comment] 2022-09-22 03:10
Seems to be running fine with the SU10 version as well.   I'll update the docs with the next release.

Duplicate of #18

**Closed as completed by dementedmonkey** 2022-09-22 03:10 UTC
