### ISSUE TITLE
PROGRESS page flickers

### ISSUE THREAD

**Issue by tigert** [dementedmonkey/cj4-mcdu#20] opened 2022-05-14 12:00 UTC
Hey, thanks for a great mod.

Noticed the progress page (INDEX -> PROG) flickers, it seems it is updating the values, but draws first the fields with dashes ("-----") before updating them with the real data.

**Comment by dementedmonkey** [comment] 2022-05-15 16:41
The fix for this is already checked in, I just haven't gotten around to making a release containing it.

Duplicate of #7

**Closed as completed by dementedmonkey** 2022-05-15 16:41 UTC
